### PR TITLE
testing longer await in publish

### PR DESCRIPTION
**Pull request by lewisjkl**

### CODE REVIEW

**Comment by ckipp01** [comment]
_Creeping here a bit_

I'm assuming the longer timeout fixed stuff? When I first created `mill-ci-release` I was curious about this and considered just going longer by default. Seeing that this was an issue here, I may just do that.

**Comment by daddykotex** [comment]
It was not an issue. There was an actual problem with the repository in staging.

There were missing information for the poms (developers and licenses): https://github.com/disneystreaming/alloy/pull/13

If instead that information can be surfaced from the API, that'd be best

**Comment by Baccata** [comment]
@ckipp01 issue was unrelated, @lewisjkl didn't have access to the sonatype account we're using to publish so he couldn't see the error (that totally doesn't get reported to the http caller ... why ? "because f*** you, that's why"). 

Sonatype requires both the licence to be there in the POM, and for at least one developer to be listed. It wasn't the case, publish was failing for no reasons, @lewisjkl took a stab in the dark. I assume we can rollback the change.

**Comment by ckipp01** [comment]
Ah ok cool cool. Either way I may bump the defaults a bit. I know it's not configurable at the moment, so maybe having a bit longer defaults is better anyways. Either way, glad to see it being used!

**Pull request merged**
