### PR TITLE
Enable sparse collection tests

### PR DESCRIPTION
**Pull request by Baccata**

### CODE REVIEW

**Review by daddykotex — COMMENTED** [review]
LGTM, can I ask you to add those on top: https://github.com/disneystreaming/smithy4s/pull/987#issuecomment-1567466137 ?

**Comment by Baccata** [comment]
@daddykotex I had a check and some of those tests should actually be disallowed, because they are passing for accidental reasons (ie how we recover error types based on status codes for instance). 

I think we need to change the model of the test config

**Comment by Baccata** [comment]
I'll merge this to unblock my current smithy4s PR and will circle back

**Comment by daddykotex** [comment]
Ah good catch

**Comment by kubukoz** [comment]
circle back? whatchu gonna do next, touch base?

**Comment by Baccata** [comment]
I'll hire key people to set up some scrum process and groom the backlog.

**Pull request merged**
